#!/bin/sh

# This script is run when the cids (capstone ids) is first started. It does the following:
# 1.) Ensures all necessary dependencies are installed (python3, python3-pip, misc pip packages, etc.)
# 2.) Checks the config file /etc/capstone-ids/config.json that it is properly setup with email account information and MAC addresses for IoT devices
# 3.) Start the actual IDS program (probably called cids-main or something similar)


# Update the package repositories for OpenWrt
opkg update

# Make sure Python3, Pip, misc packages are installed
opkg install python3
opkg install python3-pip
pip3 install scapy
pip3 install dataclasses

# set config path environment variable
export IOT_IDS_CONFIGPATH = "/etc/tinyHIPPO/config.json"

# Start the actual program
# TODO: /etc/capstone-ids/
