#!/bin/sh

# This script is run when the cids (capstone ids) is first started. It does the following:
# 1.) Ensures all necessary dependencies are installed (python3, python3-pip, misc pip packages, etc.)
# 2.) Call the script to initialize the sqlite database
# 3.) Start the actual IDS program (probably called cids-main or something similar)


# Update the package repositories for OpenWrt
opkg update

# Make sure Python3, Pip, misc packages are installed
pip3 install scapy
pip3 install dataclasses
pip3 install requests
pip3 install python-nmap

# set install path environment variable
export TINYHIPPO_INSTALL_PATH='/etc/tinyHIPPO'

# Move the dashboard files
# TODO: this is a hack to get tinyHIPPO running for the midterm progress report
cp -r $TINYHIPPO_INSTALL_PATH/src/dashboard/luasrc/controller/ids-priv /usr/lib/lua/luci/controller
cp -r $TINYHIPPO_INSTALL_PATH/src/dashboard/luasrc/view/ids-priv /usr/lib/lua/luci/view

# Restart the webserver
uci set luci.ccache.enable=0
uci commit luci
/etc/init.d/uhttpd restart

# Create and populate the sqlite database
sqlite3 $TINYHIPPO_INSTALL_PATH/tinyHIPPO.db < $TINYHIPPO_INSTALL_PATH/tinyHIPPO_db_setup.sql
sqlite3 $TINYHIPPO_INSTALL_PATH/tinyHIPPO.db < $TINYHIPPO_INSTALL_PATH/tinyHIPPO_populate_equations.sql

# Start the actual program
$TINYHIPPO_INSTALL_PATH/tiny_hippo_run.py &
$TINYHIPPO_INSTALL_PATH/run_flask.py &
