---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by elhel.
--- DateTime: 4/7/2021 3:35 PM
---

function format_ip_neighbors(data)
    local return_string = [[
    <table class="notification_table" >
        <tr>
            <th></th>
            <th>IP Address</th>
            <th>MAC Address</th>
            <th>Interface</th>
        </tr>
    ]]

    local config_count = 1

    for line in string.gmatch(data, '[^\r\n]+') do
        local array = {}
        if (line ~= nil) then
            for word in string.gmatch(line, "%S+") do
                if (word ~= nil and word ~= '') then
                    table.insert(array, word)
                end
            end
            interface = array[3]
            ip = array[1]
            -- Match only standard hex MAC addresses
            mac = string.match(array[5], "(%x+:%x+:%x+:%x+:%x+:%x+)")
            if (ip ~= nil and ip ~= '' and mac ~= nil and mac ~= '') then
                return_string = return_string .. "<tr id=\"config_row_" .. tostring(config_count) .. "\">"  .. "\n"
                return_string = return_string .. "<td <input type=\"checkbox\" class=\"row_selector row_" .. tostring(config_count) .. "\" id=\"selector_" .. tostring(config_count) .. "\">   &nbsp;   </td>" .. "\n"
                return_string = return_string .. "<td class=\"ip row_" .. tostring(config_count) .. "\">" .. ip .. "</td>" .. "\n"
                return_string = return_string .. "<td class=\"mac row_" .. tostring(config_count) .. "\">" .. mac .. "</td>" .. "\n"
                return_string = return_string .. "<td class=\"int row_" .. tostring(config_count) .. "\">" .. interface .. "</td>" .. "\n"
                return_string = return_string .. "</tr>" .. "\n"
                config_count = config_count + 1
            end
        end
    end
    return_string = return_string .. "</table>"
    return return_string
end

local data = format_ip_neighbors(luci.sys.exec("ip neigh"))